ControleDeAcesso.Web/Controllers/GrupoController.cs
using ControleDeAcesso.Aplicacao;
using ControleDeAcesso.Dominio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleDeAcesso.Web.Controllers
{
    public class GrupoController : Controller
    {
        // GET: Grupo
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult HomeGrupo()
        {
            ViewBag.Titulo = "Manutenção de Grupos";
            var groupAplication = GrupoAplicacaoConstrutor.grupoAp();
            var listaDeTodosGrupos = groupAplication.ListarTodos();
            return View(listaDeTodosGrupos);
        }

        public ActionResult CadastrarGrupo()
        {

            return View();
        }

        [HttpPost]
        public ActionResult CadastrarGrupo(Grupo grupo)
        {
            if (ModelState.IsValid)
            {
                var groupAplication = GrupoAplicacaoConstrutor.grupoAp();
                groupAplication.Salvar(grupo);
                return RedirectToAction("HomeGrupo");
            }

            return View();
        }
    }
}

ControleDeAcesso.Web/Controllers/HomeController.cs
using ControleDeAcesso.Aplicacao;
using ControleDeAcesso.Dominio;
using System.Collections.Generic;
using System.Web.Mvc;


namespace ControleDeAcesso.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {

            return View();
        }

       
        public ActionResult HomeSistema()
        {
            ViewBag.Titulo = "Manutenção de Sistemas";
            return View();
        }
        public ActionResult HomePermissao()
        {
            ViewBag.Titulo = "Manutenção de Permissões";
            return View();
        }
        public ActionResult HomeGrupo()
        {
            ViewBag.Titulo = "Manutenção de Grupos";
            return View();
        }


    }
}

ControleDeAcesso.Web/Controllers/PermissaoController.cs
using ControleDeAcesso.Aplicacao;
using ControleDeAcesso.Dominio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleDeAcesso.Web.Controllers
{
    public class PermissaoController : Controller
    {
        // GET: Permissao
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult HomePermissao()
        {
            ViewBag.Titulo = "Manutenção de Permissões";
            var permissionAplication = PermissaoAplicacaoConstrutor.PermissaoAp();
            var listaDeTodasPermissoes = permissionAplication.ListarTodos();
            return View(listaDeTodasPermissoes);
        }

        public ActionResult CadastrarPermissao()
        {

            return View();
        }

        [HttpPost]
        public ActionResult CadastrarPermissao(Permissao permissao)
        {
            if (ModelState.IsValid)
            {
                var permissionAplication = PermissaoAplicacaoConstrutor.PermissaoAp();
                permissionAplication.Salvar(permissao);

                return RedirectToAction("HomePermissao");
            }

            return View();
        }
    }
}

ControleDeAcesso.Web/Controllers/SistemaController.cs
using ControleDeAcesso.Aplicacao;
using ControleDeAcesso.Dominio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleDeAcesso.Web.Controllers
{
    public class SistemaController : Controller
    {
        // GET: Sistema
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult HomeSistema()
        {
            ViewBag.Titulo = "Manutenção de Sistemas";
            var systemAplication = SistemaAplicacaoConstrutor.sistemaAp();
            var listaDeTodosSistemas = systemAplication.ListarTodos();
            return View(listaDeTodosSistemas);
        }

        public ActionResult CadastrarSistema()
        {

            return View();
        }
        [HttpPost]
        public ActionResult CadastrarSistema(Sistema sistema)
        {
            if (ModelState.IsValid)
            {
                var systemAplication = SistemaAplicacaoConstrutor.sistemaAp();
                systemAplication.Salvar(sistema);

                return RedirectToAction("HomeSistema");
            }

            return View();
        }

    }
}

ControleDeAcesso.Web/Controllers/UsuarioController.cs
using ControleDeAcesso.Aplicacao;
using ControleDeAcesso.Dominio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleDeAcesso.Web.Controllers
{
    public class UsuarioController : Controller
    {
        // GET: Usuario
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult HomeUsuario()
        {
            ViewBag.Titulo = "Manutenção de Usuários";
            var userAplication = UsuarioAplicacaoConstrutor.UsuarioAp();
            var listaDeTodosUsuarios = userAplication.ListarTodos();
            return View(listaDeTodosUsuarios);
        }

        public ActionResult CadastroUsuario()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CadastroUsuario(Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                var apUser = UsuarioAplicacaoConstrutor.UsuarioAp();
                apUser.Salvar(usuario);
                return RedirectToAction("HomeUsuario");
            }

            return View();
        }
    }
}

ControleDeAcesso.Web/Views/Grupo/CadastrarGrupo.cshtml
@model ControleDeAcesso.Dominio.Grupo

@{
    ViewBag.Title = "Cadastrar Grupo";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h2>Cadastrar Grupo</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
                @Html.LabelFor(model => model.idGrupo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.idGrupo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.idGrupo, "", new { @class = "text-danger" })
                </div>
            </div>*@
        <div class="container">
            <div class="form-group">
                @Html.LabelFor(model => model.Nome)
                <div>
                    @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control", @placeholder="Digite o nome" } })
                    @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div>
                    <input type="submit" value="Cadastrar" class="btn btn-primary" />
                    @Html.ActionLink("Voltar", "HomeGrupo", "Grupo", new { @class = "btn btn-primary" })

                </div>
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ControleDeAcesso.Web/Views/Grupo/HomeGrupo.cshtml
@model IEnumerable<ControleDeAcesso.Dominio.Grupo>

@{
    ViewBag.Title = "HomeGrupo";
}

<h2>@ViewBag.Titulo</h2>
<hr />
<p>
    @Html.ActionLink("Novo Grupo", "CadastrarGrupo", "Grupo", new { @class = "btn btn-primary pull-right" })
</p>
<br />
<br />
<div class="panel panel-primary">
    <div class="panel-heading">     
    </div>
    <table class="table table-bordered table-responsive table-hover text-center">
        <tr>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.Codigo)
            </th>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Codigo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.ActionLink("Detalhes", "Edit", new { /* id=item.PrimaryKey */@class="btn btn-primary" })
                    @*@Html.ActionLink("Detalhar", "Details", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Excluir", "Delete", new { /* id=item.PrimaryKey */ })*@
                </td>
            </tr>
        }

    </table>
</div>

ControleDeAcesso.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ControleDeAcesso.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ControleDeAcesso.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1 class="text-center">Controle de Acesso</h1>
    <p class="text-center">Sistema para controle de Úsuarios, Grupos, Permissões e Aplicações dos softwares gerenciados.</p>
    @*<p><a href="https://asp.net" class="btn btn-primary btn-lg">Saiba Mais &raquo;</a></p>*@
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

ControleDeAcesso.Web/Views/Permissao/CadastrarPermissao.cshtml
@model ControleDeAcesso.Dominio.Permissao

@{
    ViewBag.Title = "Cadastrar Permissao";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h2>Cadastrar Permissão</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
                @Html.LabelFor(model => model.idPermissao, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.idPermissao, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.idPermissao, "", new { @class = "text-danger" })
                </div>
            </div>*@
        <div class="container">
            <div class="form-group">
                <div>
                    @Html.LabelFor(model => model.Nome)

                </div>
                <div >
                    @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control",@placeholder="Digite o nome" } })
                    @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div>
                    <input type="submit" value="Cadastrar" class="btn btn-primary" />
                    @Html.ActionLink("Voltar", "HomePermissao", "Permissao", new { @class = "btn btn-primary" })
                </div>
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ControleDeAcesso.Web/Views/Permissao/HomePermissao.cshtml
@model IEnumerable<ControleDeAcesso.Dominio.Permissao>

@{
    ViewBag.Title = "HomePermissao";
}

<h2>@ViewBag.Titulo</h2>
<hr />
<p>
    @Html.ActionLink("Nova Permissão", "CadastrarPermissao", "Permissao", new { @class = "btn btn-primary pull-right" })
</p>
<br />
<br />
<div class="panel panel-primary">
    <div class="panel-heading">
    </div>
    <table class="table table-bordered table-responsive table-hover text-center">
        <tr>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.Codigo)
            </th>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.Codigo)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td class="text-center">
                    @Html.ActionLink("Detalhes", "Edit", new { /* id=item.PrimaryKey */@class = "btn btn-primary" })
                    @*@Html.ActionLink("Detalhar", "Details", new { /* id=item.PrimaryKey */ }) |
                        @Html.ActionLink("Excluir", "Delete", new { /* id=item.PrimaryKey */ })*@
                </td>
            </tr>
        }

    </table>
</div>

ControleDeAcesso.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Controle de Acesso</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Controle de Acesso", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Usuario", "HomeUsuario", "Usuario")</li>
                    <li>@Html.ActionLink("Sistema", "HomeSistema", "Sistema")</li>
                    <li>@Html.ActionLink("Permissao", "HomePermissao", "Permissao")</li>
                    <li>@Html.ActionLink("Grupo", "HomeGrupo", "Grupo")</li>
                    @*<li>@Html.ActionLink("Log", "HomeLog", "Log")</li>*@
                </ul>
            </div>
        </div>
    </div>
    <br />
    
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            @*<p>&copy; @DateTime.Now.Year - Controle de Acesso</p>*@
            <div class="container">
                <div class="row">
                    <div class="col-md-4">
                        <p>
                            <p>&copy; 2018 - Controle de Acesso</p>
                        </p>
                    </div>
                    <div class="col-md-4 text-center">
                        <p>
                            <p>v1.0.0</p>
                        </p>

                    </div>
                    <div class="col-md-4 text-right">

                        <p>
                            <p>&copy; security</p>
                        </p>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ControleDeAcesso.Web/Views/Sistema/CadastrarSistema.cshtml
@model ControleDeAcesso.Dominio.Sistema

@{
    ViewBag.Title = "Cadastrar Sistema";
}

<div class="container">
    <h2>Cadastrar Sistema</h2>
    <hr />
</div>

<div class="container">

    <div class="row">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal pull-left">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @*<div class="form-group">
                        @Html.LabelFor(model => model.idSistema, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.idSistema, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.idSistema, "", new { @class = "text-danger" })
                        </div>
                    </div>*@

                <div class="container">
                    <div class="form-group">
                        <div>
                            @Html.LabelFor(model => model.Nome)
                        </div>
                        <div>
                            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control", @placeholder="Digite o nome" } })
                            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div>
                            @Html.LabelFor(model => model.Descricao)
                        </div>
                        <div>
                            @Html.TextAreaFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control", @placeholder="Digite a descrição" } })
                            @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div>
                            <input type="submit" value="Cadastrar" class="btn btn-primary" />
                            @Html.ActionLink("Voltar", "HomeSistema", "Sistema", new { @class = "btn btn-primary" })

                        </div>
                    </div>
                </div>
            </div>
        }



    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ControleDeAcesso.Web/Views/Sistema/HomeSistema.cshtml
@model IEnumerable<ControleDeAcesso.Dominio.Sistema>

@{
    ViewBag.Title = "HomeSistema";
}

<h2> @ViewBag.Titulo </h2>
<hr />

<p>
    @Html.ActionLink("Novo Sistema", "CadastrarSistema", "Sistema", new { @class = "btn btn-primary pull-right" })
</p>

<br />
<br />
<div class="panel panel-primary">
    <div class="panel-heading">
    </div>
    <table class="table table-bordered table-responsive table-hover text-center">
        <tr>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.Codigo)
            </th>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.Descricao)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Codigo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Descricao)
                </td>
                <td>
                    @Html.ActionLink("Detalhes", "Edit", new { /* id=item.PrimaryKey */@class = "btn btn-primary" })
                    @*@Html.ActionLink("Detalhar", "Details", new { /* id=item.PrimaryKey */ }) |
                        @Html.ActionLink("Excluir", "Delete", new { /* id=item.PrimaryKey */ })*@
                </td>
            </tr>
        }

    </table>
</div>

ControleDeAcesso.Web/Views/Usuario/CadastroUsuario.cshtml
@model ControleDeAcesso.Dominio.Usuario

@{
    ViewBag.Title = "Cadastro Usuario";

}

<div class="container">
    <h2>Cadastrar Usuario</h2>
    <hr />

</div>
<div class="container">
    <div class="row">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal pull-left">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @*<div class="form-group">
                        @Html.LabelFor(model => model.idUsuario, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.idUsuario, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.idUsuario, "", new { @class = "text-danger" })
                        </div>
                    </div>*@
                <div class="container">
                    <div class="form-group">
                        <div>
                            @Html.LabelFor(model => model.Email)
                        </div>
                        <div>
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @placeholder = "Digite seu email@" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div>
                            @Html.LabelFor(model => model.Senha)

                        </div>
                        <div>
                            @Html.EditorFor(model => model.Senha, new { htmlAttributes = new { @class = "form-control", @placeholder = "Digite sua senha" } })
                            @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div>
                            <input type="submit" value="Cadastrar" class="btn btn-primary" />
                            @Html.ActionLink("Voltar", "HomeUsuario", "Usuario", new { @class = "btn btn-primary" })
                        </div>
                    </div>
                </div>
            </div>

        }
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ControleDeAcesso.Web/Views/Usuario/HomeUsuario.cshtml
@model IEnumerable<ControleDeAcesso.Dominio.Usuario>

@{
    ViewBag.Title = "HomeUsuario";
}

<h2>@ViewBag.Titulo</h2>
<hr />

<p>
    @Html.ActionLink("Novo Usuario", "CadastroUsuario", "Usuario", new { @class = "btn btn-primary pull-right" })
</p>
<br />
<br />
<div class="panel panel-primary">
    <div class="panel-heading">        
    </div>
    <table class="table table-bordered table-responsive table-hover text-center">
        <tr>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.Codigo)
            </th>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.Senha)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Codigo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Senha)
                </td>
                <td>
                    @Html.ActionLink("Detalhes", "Edit", new { /* id=item.PrimaryKey */ @class = "btn btn-primary" })
                    @*@Html.ActionLink("Detalhar", "Details", new { /* id=item.PrimaryKey */ }) |
                        @Html.ActionLink("Excluir", "Delete", new { /* id=item.PrimaryKey */ })*@
                </td>
            </tr>
        }

    </table>
</div>